server:
  port: 8080
spring:
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate.ddl-auto: update